apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: yamle-encrypter
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["test-public"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: yamle-decrypter
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["test"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: yamle-admin
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["test", "test-public"]
  verbs: ["get", "create"]
